[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"
TZ = "Europe/Amsterdam"

[context.deploy-preview.environment]
HUGO_VERSION = "0.78.2"
command = "hugo -b $DEPLOY_URL"